spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aledh.mailsender@gmail.com
    password: pw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
